#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成数据库 Schema
从设计文档生成 SQL DDL 和 Prisma schema
"""

import os
from pathlib import Path


def generate_sql_ddl(entities: list, output_file: str = "docs/schema.sql"):
    """生成 SQL DDL"""
    
    sql_lines = ["-- Database Schema", "-- Generated by se-detailed-design", ""]
    
    for entity in entities:
        table_name = entity["name"].lower()
        sql_lines.append(f"-- Table: {entity['name']}")
        sql_lines.append(f"CREATE TABLE {table_name} (")
        
        columns = []
        for attr in entity.get("attributes", []):
            col_def = f"    {attr['name']} {attr['type']}"
            if attr.get("primary_key"):
                col_def += " PRIMARY KEY"
            if attr.get("not_null"):
                col_def += " NOT NULL"
            if attr.get("unique"):
                col_def += " UNIQUE"
            if attr.get("default"):
                col_def += f" DEFAULT {attr['default']}"
            columns.append(col_def)
        
        # 外键约束
        for attr in entity.get("attributes", []):
            if attr.get("foreign_key"):
                ref_table = attr["references"]["table"]
                ref_col = attr["references"]["column"]
                columns.append(f"    CONSTRAINT fk_{table_name}_{attr['name']} "
                             f"FOREIGN KEY ({attr['name']}) REFERENCES {ref_table}({ref_col})")
        
        sql_lines.append(",\n".join(columns))
        sql_lines.append(");")
        sql_lines.append("")
    
    # 保存文件
    Path(output_file).parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))
    
    print(f"✓ Schema 已生成：{output_file}")
    return "\n".join(sql_lines)


def generate_prisma_schema(entities: list, output_file: str = "prisma/schema.prisma"):
    """生成 Prisma schema"""
    
    lines = [
        "// This is your Prisma schema file",
        "// Generated by se-detailed-design",
        "",
        "generator client {",
        "  provider = \"prisma-client-js\"",
        "}",
        "",
        'datasource db {',
        '  provider = "postgresql"',
        '  url      = env("DATABASE_URL")',
        "}",
        ""
    ]
    
    for entity in entities:
        model_name = entity["name"]
        lines.append(f"model {model_name} {{")
        
        for attr in entity.get("attributes", []):
            field_def = f"  {attr['name']} {attr['type']}"
            if attr.get("primary_key"):
                field_def += " @id"
            if attr.get("unique"):
                field_def += " @unique"
            if attr.get("default"):
                field_def += f" @default({attr['default']})"
            if attr.get("relation"):
                rel = attr["relation"]
                field_def += f' @relation("{rel["name"]}", references: [{rel["references"]}])'
            lines.append(field_def)
        
        lines.append("}")
        lines.append("")
    
    # 保存文件
    Path(output_file).parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    
    print(f"✓ Prisma schema 已生成：{output_file}")
    return "\n".join(lines)


def generate_api_routes(apis: list, output_file: str = "docs/api_routes.md"):
    """生成 API 路由文档"""
    
    lines = ["# API 路由文档", "", "## 路由列表", ""]
    
    for api in apis:
        method = api.get("method", "GET")
        path = api["path"]
        desc = api.get("description", "")
        
        lines.append(f"### {method} {path}")
        lines.append(f"**描述**: {desc}")
        lines.append("")
        
        if "request" in api:
            lines.append("**请求体**:")
            lines.append("```json")
            lines.append(str(api["request"]))
            lines.append("```")
            lines.append("")
        
        if "response" in api:
            lines.append("**响应体**:")
            lines.append("```json")
            lines.append(str(api["response"]))
            lines.append("```")
            lines.append("")
        
        lines.append("---")
        lines.append("")
    
    # 保存文件
    Path(output_file).parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    
    print(f"✓ API 路由已生成：{output_file}")
    return "\n".join(lines)


if __name__ == "__main__":
    # 示例：生成用户实体 schema
    entities = [
        {
            "name": "User",
            "attributes": [
                {"name": "id", "type": "VARCHAR(36)", "primary_key": True},
                {"name": "username", "type": "VARCHAR(50)", "not_null": True, "unique": True},
                {"name": "email", "type": "VARCHAR(100)", "not_null": True, "unique": True},
                {"name": "password_hash", "type": "VARCHAR(255)", "not_null": True},
                {"name": "created_at", "type": "TIMESTAMP", "default": "CURRENT_TIMESTAMP"}
            ]
        }
    ]
    
    generate_sql_ddl(entities)
    generate_prisma_schema(entities)
